version: "3.9"
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: ./gateway/Nginx.Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - user-service
      - trip-service
      - driver-service

  user-service:
    build:
      context: .
      dockerfile: ./deploy/docker/UserService.Dockerfile
    environment:
      - ConnectionStrings__Default=Host=postgres-user;Port=5432;Database=uitgo_user;Username=postgres;Password=postgres
      - Jwt__Secret=PLEASE_CHANGE_THIS_DEMO_SECRET
    depends_on:
      - postgres-user
    ports:
      - "5001:8080"

  trip-service:
    build:
      context: .
      dockerfile: ./deploy/docker/TripService.Dockerfile
    environment:
      - ConnectionStrings__Default=Host=postgres-trip;Port=5432;Database=uitgo_trip;Username=postgres;Password=postgres
    depends_on:
      - postgres-trip
      - driver-service
    ports:
      - "5002:8080"

  driver-service:
    build:
      context: .
      dockerfile: ./deploy/docker/DriverService.Dockerfile
    environment:
      - ConnectionStrings__Default=Host=postgres-driver;Port=5432;Database=uitgo_driver;Username=postgres;Password=postgres
    depends_on:
      - postgres-driver
    ports:
      - "5003:8080"

  postgres-user:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uitgo_user
    ports:
      - "5433:5432"
    volumes:
      - pg_user:/var/lib/postgresql/data

  postgres-trip:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uitgo_trip
    ports:
      - "5434:5432"
    volumes:
      - pg_trip:/var/lib/postgresql/data

  postgres-driver:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uitgo_driver
    ports:
      - "5435:5432"
    volumes:
      - pg_driver:/var/lib/postgresql/data

volumes:
  pg_user: {}
  pg_trip: {}
  pg_driver: {}
